In [2]:
import pandas as pd
df= pd.read_csv('mental_health.csv')

In [4]:
df.shape

(2000, 18)

In [5]:
row , col =df.shape

In [6]:
row

2000

In [7]:
col

18

In [8]:
df.head()

,Person_ID,Age,Gender,Occupation,Daily_Screen_Time,Social_Media_Usage,Night_Usage,Sleep_Hours,Stress_Level,Work_Study_Hours,Physical_Activity,Social_Interaction_Score,Caffeine_Intake,Smoking,Alcohol,Depression,Anxiety,Burnout
0,1,54,Male,Student,10.2,7.5,0,6.5,8,5.8,Low,6,2,0,1,1,1,1
1,2,44,Male,Student,6.8,4.5,0,5.1,4,7.9,High,2,1,1,0,0,0,0
2,3,30,Male,Employed,5.5,6.9,0,3.5,10,9.4,Low,2,0,1,1,1,0,1
3,4,58,Male,Employed,5.6,4.1,0,9.0,2,2.0,High,10,0,0,1,0,0,0
4,5,23,Female,Employed,10.1,6.0,1,3.8,4,4.6,Low,4,4,0,1,1,1,0

In [9]:
#top nth row
df.head(8)

,Person_ID,Age,Gender,Occupation,Daily_Screen_Time,Social_Media_Usage,Night_Usage,Sleep_Hours,Stress_Level,Work_Study_Hours,Physical_Activity,Social_Interaction_Score,Caffeine_Intake,Smoking,Alcohol,Depression,Anxiety,Burnout
0,1,54,Male,Student,10.2,7.5,0,6.5,8,5.8,Low,6,2,0,1,1,1,1
1,2,44,Male,Student,6.8,4.5,0,5.1,4,7.9,High,2,1,1,0,0,0,0
2,3,30,Male,Employed,5.5,6.9,0,3.5,10,9.4,Low,2,0,1,1,1,0,1
3,4,58,Male,Employed,5.6,4.1,0,9.0,2,2.0,High,10,0,0,1,0,0,0
4,5,23,Female,Employed,10.1,6.0,1,3.8,4,4.6,Low,4,4,0,1,1,1,0
5,6,36,Female,Student,5.3,6.1,1,3.4,2,7.4,Low,8,2,1,0,1,0,0
6,7,54,Female,Unemployed,4.1,2.2,0,8.3,3,7.3,Low,5,4,1,1,1,0,0
7,8,34,Male,Unemployed,2.8,3.5,1,4.8,4,8.4,Medium,9,0,1,0,0,0,1

In [10]:
# last nth row
df.tail(10)

,Person_ID,Age,Gender,Occupation,Daily_Screen_Time,Social_Media_Usage,Night_Usage,Sleep_Hours,Stress_Level,Work_Study_Hours,Physical_Activity,Social_Interaction_Score,Caffeine_Intake,Smoking,Alcohol,Depression,Anxiety,Burnout
1990,1991,53,Male,Unemployed,8.3,2.8,1,7.7,4,8.0,Medium,2,4,0,0,1,1,1
1991,1992,19,Male,Student,6.2,1.1,1,6.6,8,11.2,Medium,8,1,0,1,0,0,1
1992,1993,53,Female,Student,3.7,2.6,0,6.9,1,11.2,Medium,10,4,1,0,0,0,0
1993,1994,34,Female,Student,11.9,1.4,0,7.5,10,4.9,High,4,4,0,1,0,1,0
1994,1995,21,Male,Unemployed,10.2,1.7,1,3.7,3,9.4,High,7,0,1,0,0,1,1
1995,1996,49,Female,Employed,4.8,4.0,1,8.0,1,9.8,Medium,5,0,1,1,1,0,0
1996,1997,33,Male,Employed,2.7,2.6,0,7.2,9,10.1,Low,8,1,1,1,1,1,1
1997,1998,28,Male,Employed,2.6,4.6,0,6.5,10,7.7,Medium,6,2,0,0,0,1,1
1998,1999,56,Female,Student,3.2,2.8,1,8.3,9,2.1,High,5,0,1,1,0,0,0
1999,2000,38,Male,Unemployed,7.8,7.6,0,7.2,7,9.6,Low,1,3,0,1,1,0,1

In [11]:
# range of entries
df[5:10]

,Person_ID,Age,Gender,Occupation,Daily_Screen_Time,Social_Media_Usage,Night_Usage,Sleep_Hours,Stress_Level,Work_Study_Hours,Physical_Activity,Social_Interaction_Score,Caffeine_Intake,Smoking,Alcohol,Depression,Anxiety,Burnout
5,6,36,Female,Student,5.3,6.1,1,3.4,2,7.4,Low,8,2,1,0,1,0,0
6,7,54,Female,Unemployed,4.1,2.2,0,8.3,3,7.3,Low,5,4,1,1,1,0,0
7,8,34,Male,Unemployed,2.8,3.5,1,4.8,4,8.4,Medium,9,0,1,0,0,0,1
8,9,38,Male,Employed,6.7,5.5,0,6.9,4,5.0,Low,4,1,0,0,0,1,0
9,10,26,Male,Employed,6.8,1.5,0,5.0,10,7.4,Medium,3,3,1,0,1,1,1

In [12]:
#accesing the columns
df.Age

0       54
1       44
2       30
3       58
4       23
        ..
1995    49
1996    33
1997    28
1998    56
1999    38
Name: Age, Length: 2000, dtype: int64

In [13]:
df.Daily_Screen_Time

0       10.2
1        6.8
2        5.5
3        5.6
4       10.1
        ...
1995     4.8
1996     2.7
1997     2.6
1998     3.2
1999     7.8
Name: Daily_Screen_Time, Length: 2000, dtype: float64

In [14]:
df.columns

Index(['Person_ID', 'Age', 'Gender', 'Occupation', 'Daily_Screen_Time',
       'Social_Media_Usage', 'Night_Usage', 'Sleep_Hours', 'Stress_Level',
       'Work_Study_Hours', 'Physical_Activity', 'Social_Interaction_Score',
       'Caffeine_Intake', 'Smoking', 'Alcohol', 'Depression', 'Anxiety',
       'Burnout'],
      dtype='object')

In [15]:
#accesing nth column
df[['Occupation']].head()

  Occupation
0    Student
1    Student
2   Employed
3   Employed
4   Employed

In [16]:
df[['Age','Gender']]

      Age  Gender
0      54    Male
1      44    Male
2      30    Male
3      58    Male
4      23  Female
...   ...     ...
1995   49  Female
1996   33    Male
1997   28    Male
1998   56  Female
1999   38    Male

[2000 rows x 2 columns]

In [18]:
type(df['Age'])

pandas.core.series.Series

In [19]:
type(df[['Age']])

pandas.core.frame.DataFrame

## Basic Statiscal Functions

In [20]:
url='https://raw.githubusercontent.com/HabibaMaisa/Pandas_learning/refs/heads/main/mental_health.csv'
df=pd.read_csv(url)
df.head()

,Person_ID,Age,Gender,Occupation,Daily_Screen_Time,Social_Media_Usage,Night_Usage,Sleep_Hours,Stress_Level,Work_Study_Hours,Physical_Activity,Social_Interaction_Score,Caffeine_Intake,Smoking,Alcohol,Depression,Anxiety,Burnout
0,1,54,Male,Student,10.2,7.5,0,6.5,8,5.8,Low,6,2,0,1,1,1,1
1,2,44,Male,Student,6.8,4.5,0,5.1,4,7.9,High,2,1,1,0,0,0,0
2,3,30,Male,Employed,5.5,6.9,0,3.5,10,9.4,Low,2,0,1,1,1,0,1
3,4,58,Male,Employed,5.6,4.1,0,9.0,2,2.0,High,10,0,0,1,0,0,0
4,5,23,Female,Employed,10.1,6.0,1,3.8,4,4.6,Low,4,4,0,1,1,1,0

In [21]:
df.index

RangeIndex(start=0, stop=2000, step=1)

In [22]:
len(df)

2000

In [23]:
#MAX
df['Daily_Screen_Time'].max()

12.0

In [24]:
#MIN
df['Daily_Screen_Time'].min()

2.0

In [25]:
df['Daily_Screen_Time'].mean()

np.float64(6.943149999999999)

In [26]:
df['Daily_Screen_Time'].std()

2.8824151741409647

In [27]:
df['Daily_Screen_Time'].mode()

0    7.8
Name: Daily_Screen_Time, dtype: float64

In [29]:
df['Daily_Screen_Time'].value_counts()

Daily_Screen_Time
7.8     34
8.8     31
8.0     31
3.3     29
2.5     28
        ..
5.7     11
7.2     11
12.0     9
2.0      6
9.9      6
Name: count, Length: 101, dtype: int64

In [31]:
#25%
df['Daily_Screen_Time'].quantile(0.25)

np.float64(4.5)

In [32]:
#100%
df['Daily_Screen_Time'].quantile(1)

np.float64(12.0)

In [33]:
df['Daily_Screen_Time'].quantile(0)

np.float64(2.0)

In [34]:
df.describe()

,Person_ID,Age,Daily_Screen_Time,Social_Media_Usage,Night_Usage,Sleep_Hours,Stress_Level,Work_Study_Hours,Social_Interaction_Score,Caffeine_Intake,Smoking,Alcohol,Depression,Anxiety,Burnout
count,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.00000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000
mean,1000.500000,37.694000,6.943150,4.436400,0.489500,6.00765,5.409500,7.005650,5.488000,2.029500,0.492000,0.513000,0.499000,0.505500,0.515500
std,577.494589,12.614195,2.882415,2.011725,0.500015,1.70631,2.885129,2.846442,2.885484,1.432709,0.500061,0.499956,0.500124,0.500095,0.499885
min,1.000000,16.000000,2.000000,1.000000,0.000000,3.00000,1.000000,2.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,500.750000,27.000000,4.500000,2.700000,0.000000,4.60000,3.000000,4.500000,3.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,1000.500000,38.000000,6.800000,4.400000,0.000000,6.00000,5.000000,7.100000,6.000000,2.000000,0.000000,1.000000,0.000000,1.000000,1.000000
75%,1500.250000,49.000000,9.400000,6.200000,1.000000,7.50000,8.000000,9.400000,8.000000,3.000000,1.000000,1.000000,1.000000,1.000000,1.000000
max,2000.000000,59.000000,12.000000,8.000000,1.000000,9.00000,10.000000,12.000000,10.000000,4.000000,1.000000,1.000000,1.000000,1.000000,1.000000

## value Sorting

In [35]:
df.head()

,Person_ID,Age,Gender,Occupation,Daily_Screen_Time,Social_Media_Usage,Night_Usage,Sleep_Hours,Stress_Level,Work_Study_Hours,Physical_Activity,Social_Interaction_Score,Caffeine_Intake,Smoking,Alcohol,Depression,Anxiety,Burnout
0,1,54,Male,Student,10.2,7.5,0,6.5,8,5.8,Low,6,2,0,1,1,1,1
1,2,44,Male,Student,6.8,4.5,0,5.1,4,7.9,High,2,1,1,0,0,0,0
2,3,30,Male,Employed,5.5,6.9,0,3.5,10,9.4,Low,2,0,1,1,1,0,1
3,4,58,Male,Employed,5.6,4.1,0,9.0,2,2.0,High,10,0,0,1,0,0,0
4,5,23,Female,Employed,10.1,6.0,1,3.8,4,4.6,Low,4,4,0,1,1,1,0

In [36]:
df['Social_Media_Usage'].sort_values()

1079    1.0
1135    1.0
1904    1.0
1914    1.0
1445    1.0
       ...
707     8.0
940     8.0
305     8.0
1693    8.0
927     8.0
Name: Social_Media_Usage, Length: 2000, dtype: float64

In [37]:
df['Social_Media_Usage'].sort_values(ascending=False)

1693    8.0
927     8.0
1637    8.0
1780    8.0
305     8.0
       ...
919     1.0
1135    1.0
1977    1.0
304     1.0
1904    1.0
Name: Social_Media_Usage, Length: 2000, dtype: float64

In [39]:
df.nlargest(10,'Caffeine_Intake')

,Person_ID,Age,Gender,Occupation,Daily_Screen_Time,Social_Media_Usage,Night_Usage,Sleep_Hours,Stress_Level,Work_Study_Hours,Physical_Activity,Social_Interaction_Score,Caffeine_Intake,Smoking,Alcohol,Depression,Anxiety,Burnout
4,5,23,Female,Employed,10.1,6.0,1,3.8,4,4.6,Low,4,4,0,1,1,1,0
6,7,54,Female,Unemployed,4.1,2.2,0,8.3,3,7.3,Low,5,4,1,1,1,0,0
10,11,26,Male,Unemployed,10.4,3.5,1,5.3,9,3.9,Medium,10,4,0,0,1,1,0
20,21,45,Male,Unemployed,11.3,5.2,0,8.5,5,3.8,High,3,4,0,1,1,0,0
24,25,48,Male,Student,6.8,1.7,1,4.5,2,8.9,Low,3,4,0,1,0,0,0
26,27,37,Female,Student,3.6,7.1,1,3.1,7,9.0,High,6,4,1,1,0,1,1
29,30,42,Male,Employed,7.6,6.2,1,6.9,4,4.7,Medium,8,4,0,1,1,0,0
31,32,43,Female,Unemployed,2.7,4.5,0,3.3,2,6.4,Medium,4,4,1,0,0,0,1
33,34,30,Female,Unemployed,3.2,7.7,0,5.8,1,7.2,Medium,6,4,0,0,0,0,0
39,40,24,Male,Student,7.5,1.1,1,3.4,4,2.2,Low,7,4,0,0,0,0,0

In [40]:
df.nsmallest(10,'Caffeine_Intake')

,Person_ID,Age,Gender,Occupation,Daily_Screen_Time,Social_Media_Usage,Night_Usage,Sleep_Hours,Stress_Level,Work_Study_Hours,Physical_Activity,Social_Interaction_Score,Caffeine_Intake,Smoking,Alcohol,Depression,Anxiety,Burnout
2,3,30,Male,Employed,5.5,6.9,0,3.5,10,9.4,Low,2,0,1,1,1,0,1
3,4,58,Male,Employed,5.6,4.1,0,9.0,2,2.0,High,10,0,0,1,0,0,0
7,8,34,Male,Unemployed,2.8,3.5,1,4.8,4,8.4,Medium,9,0,1,0,0,0,1
11,12,39,Male,Unemployed,4.2,4.7,1,4.6,10,3.9,Medium,8,0,1,0,0,1,1
14,15,39,Male,Unemployed,10.2,6.7,1,7.3,4,3.2,High,4,0,0,1,1,0,1
16,17,37,Male,Employed,6.6,6.6,0,8.7,9,7.7,Low,8,0,0,0,1,1,0
23,24,36,Female,Employed,2.3,2.0,1,8.1,5,9.2,High,4,0,0,1,0,0,1
28,29,40,Female,Unemployed,11.7,2.5,1,8.6,5,8.7,Low,10,0,0,0,0,1,0
32,33,31,Female,Unemployed,6.2,2.1,0,8.5,8,7.6,High,6,0,1,1,0,1,0
35,36,18,Female,Student,11.4,7.0,0,7.1,1,8.5,Low,5,0,0,1,0,0,0