## Conditional Satements

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('mental_health.csv')
df.head()

,Person_ID,Age,Gender,Occupation,Daily_Screen_Time,Social_Media_Usage,Night_Usage,Sleep_Hours,Stress_Level,Work_Study_Hours,Physical_Activity,Social_Interaction_Score,Caffeine_Intake,Smoking,Alcohol,Depression,Anxiety,Burnout
0,1,54,Male,Student,10.2,7.5,0,6.5,8,5.8,Low,6,2,0,1,1,1,1
1,2,44,Male,Student,6.8,4.5,0,5.1,4,7.9,High,2,1,1,0,0,0,0
2,3,30,Male,Employed,5.5,6.9,0,3.5,10,9.4,Low,2,0,1,1,1,0,1
3,4,58,Male,Employed,5.6,4.1,0,9.0,2,2.0,High,10,0,0,1,0,0,0
4,5,23,Female,Employed,10.1,6.0,1,3.8,4,4.6,Low,4,4,0,1,1,1,0

In [3]:
df['Daily_Screen_Time'].max()

12.0

In [4]:
df['Daily_Screen_Time']>8

0        True
1       False
2       False
3       False
4        True
        ...
1995    False
1996    False
1997    False
1998    False
1999    False
Name: Daily_Screen_Time, Length: 2000, dtype: bool

In [5]:
df[df['Daily_Screen_Time']>8]

,Person_ID,Age,Gender,Occupation,Daily_Screen_Time,Social_Media_Usage,Night_Usage,Sleep_Hours,Stress_Level,Work_Study_Hours,Physical_Activity,Social_Interaction_Score,Caffeine_Intake,Smoking,Alcohol,Depression,Anxiety,Burnout
0,1,54,Male,Student,10.2,7.5,0,6.5,8,5.8,Low,6,2,0,1,1,1,1
4,5,23,Female,Employed,10.1,6.0,1,3.8,4,4.6,Low,4,4,0,1,1,1,0
10,11,26,Male,Unemployed,10.4,3.5,1,5.3,9,3.9,Medium,10,4,0,0,1,1,0
13,14,55,Female,Employed,10.1,4.3,0,5.5,9,8.9,Low,9,3,0,1,1,1,1
14,15,39,Male,Unemployed,10.2,6.7,1,7.3,4,3.2,High,4,0,0,1,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1985,1986,46,Male,Student,10.2,3.2,0,8.7,8,3.9,Low,6,1,1,1,0,1,0
1989,1990,49,Female,Student,11.8,7.0,1,5.2,4,5.4,Medium,8,2,1,0,1,1,0
1990,1991,53,Male,Unemployed,8.3,2.8,1,7.7,4,8.0,Medium,2,4,0,0,1,1,1
1993,1994,34,Female,Student,11.9,1.4,0,7.5,10,4.9,High,4,4,0,1,0,1,0
1994,1995,21,Male,Unemployed,10.2,1.7,1,3.7,3,9.4,High,7,0,1,0,0,1,1

In [6]:
#subseting rows
df[df['Occupation']=='Student']

,Person_ID,Age,Gender,Occupation,Daily_Screen_Time,Social_Media_Usage,Night_Usage,Sleep_Hours,Stress_Level,Work_Study_Hours,Physical_Activity,Social_Interaction_Score,Caffeine_Intake,Smoking,Alcohol,Depression,Anxiety,Burnout
0,1,54,Male,Student,10.2,7.5,0,6.5,8,5.8,Low,6,2,0,1,1,1,1
1,2,44,Male,Student,6.8,4.5,0,5.1,4,7.9,High,2,1,1,0,0,0,0
5,6,36,Female,Student,5.3,6.1,1,3.4,2,7.4,Low,8,2,1,0,1,0,0
15,16,18,Male,Student,5.8,4.0,1,6.1,9,3.2,Medium,9,2,1,0,0,1,0
21,22,53,Male,Student,8.8,5.4,1,3.3,3,2.0,Low,4,3,1,0,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1989,1990,49,Female,Student,11.8,7.0,1,5.2,4,5.4,Medium,8,2,1,0,1,1,0
1991,1992,19,Male,Student,6.2,1.1,1,6.6,8,11.2,Medium,8,1,0,1,0,0,1
1992,1993,53,Female,Student,3.7,2.6,0,6.9,1,11.2,Medium,10,4,1,0,0,0,0
1993,1994,34,Female,Student,11.9,1.4,0,7.5,10,4.9,High,4,4,0,1,0,1,0
1998,1999,56,Female,Student,3.2,2.8,1,8.3,9,2.1,High,5,0,1,1,0,0,0

In [8]:
df[(df['Occupation']=='Student') | (df['Occupation']=='Unemployed')]

,Person_ID,Age,Gender,Occupation,Daily_Screen_Time,Social_Media_Usage,Night_Usage,Sleep_Hours,Stress_Level,Work_Study_Hours,Physical_Activity,Social_Interaction_Score,Caffeine_Intake,Smoking,Alcohol,Depression,Anxiety,Burnout
0,1,54,Male,Student,10.2,7.5,0,6.5,8,5.8,Low,6,2,0,1,1,1,1
1,2,44,Male,Student,6.8,4.5,0,5.1,4,7.9,High,2,1,1,0,0,0,0
5,6,36,Female,Student,5.3,6.1,1,3.4,2,7.4,Low,8,2,1,0,1,0,0
6,7,54,Female,Unemployed,4.1,2.2,0,8.3,3,7.3,Low,5,4,1,1,1,0,0
7,8,34,Male,Unemployed,2.8,3.5,1,4.8,4,8.4,Medium,9,0,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1992,1993,53,Female,Student,3.7,2.6,0,6.9,1,11.2,Medium,10,4,1,0,0,0,0
1993,1994,34,Female,Student,11.9,1.4,0,7.5,10,4.9,High,4,4,0,1,0,1,0
1994,1995,21,Male,Unemployed,10.2,1.7,1,3.7,3,9.4,High,7,0,1,0,0,1,1
1998,1999,56,Female,Student,3.2,2.8,1,8.3,9,2.1,High,5,0,1,1,0,0,0
1999,2000,38,Male,Unemployed,7.8,7.6,0,7.2,7,9.6,Low,1,3,0,1,1,0,1

In [9]:
#subsetting using isin()
df['Occupation'].isin(['Student','Unemployed'])

0        True
1        True
2       False
3       False
4       False
        ...
1995    False
1996    False
1997    False
1998     True
1999     True
Name: Occupation, Length: 2000, dtype: bool

## Common Q&A

In [12]:
# show occupation= student and daily sccren time 2
df[(df['Occupation']=='Student')& (df['Daily_Screen_Time']==2)]

,Person_ID,Age,Gender,Occupation,Daily_Screen_Time,Social_Media_Usage,Night_Usage,Sleep_Hours,Stress_Level,Work_Study_Hours,Physical_Activity,Social_Interaction_Score,Caffeine_Intake,Smoking,Alcohol,Depression,Anxiety,Burnout
593,594,21,Male,Student,2.0,3.5,1,7.0,4,3.2,Medium,5,1,0,1,1,0,1
958,959,50,Female,Student,2.0,6.2,1,6.2,2,10.5,High,2,4,1,0,0,1,1
1160,1161,54,Female,Student,2.0,6.4,1,8.7,6,2.5,Low,10,2,1,1,1,0,0

In [13]:
#show occupation where daily screen time is >4

df['Occupation'][df['Daily_Screen_Time']>4]

0          Student
1          Student
2         Employed
3         Employed
4         Employed
           ...
1991       Student
1993       Student
1994    Unemployed
1995      Employed
1999    Unemployed
Name: Occupation, Length: 1578, dtype: object

In [14]:
# show the raws with minimum Daily_Screen_Time
df[df['Daily_Screen_Time']==df['Daily_Screen_Time'].min()]

,Person_ID,Age,Gender,Occupation,Daily_Screen_Time,Social_Media_Usage,Night_Usage,Sleep_Hours,Stress_Level,Work_Study_Hours,Physical_Activity,Social_Interaction_Score,Caffeine_Intake,Smoking,Alcohol,Depression,Anxiety,Burnout
311,312,48,Female,Employed,2.0,3.0,1,8.7,2,9.4,High,5,0,1,1,0,1,1
333,334,47,Female,Employed,2.0,4.8,1,6.0,9,4.2,Low,5,1,0,0,0,0,0
593,594,21,Male,Student,2.0,3.5,1,7.0,4,3.2,Medium,5,1,0,1,1,0,1
907,908,59,Female,Employed,2.0,1.6,0,8.8,3,8.8,Low,8,4,0,0,0,0,0
958,959,50,Female,Student,2.0,6.2,1,6.2,2,10.5,High,2,4,1,0,0,1,1
1160,1161,54,Female,Student,2.0,6.4,1,8.7,6,2.5,Low,10,2,1,1,1,0,0

In [16]:
#show age and occupation where dailly screen time is greater than 4
df[['Age','Occupation']][df['Daily_Screen_Time']>4]

      Age  Occupation
0      54     Student
1      44     Student
2      30    Employed
3      58    Employed
4      23    Employed
...   ...         ...
1991   19     Student
1993   34     Student
1994   21  Unemployed
1995   49    Employed
1999   38  Unemployed

[1578 rows x 2 columns]