!pip install pandas

In [1]:
import pandas as pd

In [3]:
#create a list of data
data=[1,2,3,4,5,10]

In [4]:
#create a series from the list
s=pd.Series(data)
s

0     1
1     2
2     3
3     4
4     5
5    10
dtype: int64

In [5]:
type(s)

pandas.core.series.Series

In [11]:
#creating Dataframe from series
df=pd.DataFrame(s,columns=['num'])
df

   num
0    1
1    2
2    3
3    4
4    5
5   10

In [12]:
data

[1, 2, 3, 4, 5, 10]

In [17]:
#creating dataframe from list
df1 = pd.DataFrame(data,columns=['num2'])
df1

   num2
0     1
1     2
2     3
3     4
4     5
5    10

In [20]:
#dataframe to Series
s1=df1['num2']
s1

0     1
1     2
2     3
3     4
4     5
5    10
Name: num2, dtype: int64

In [21]:
type(s)

pandas.core.series.Series

In [25]:
#Create a series for 2 integer columns
data1=[[1,2],[2,3],[3,4]]
data1

[[1, 2], [2, 3], [3, 4]]

In [26]:
type(data1)

list

In [27]:
s2=pd.Series(data1)
s2

0    [1, 2]
1    [2, 3]
2    [3, 4]
dtype: object

In [28]:
type(s2)

pandas.core.series.Series

In [30]:
#creating a Dataframe from the list and rename the colmuns
dff=pd.DataFrame(data1,columns=['num1','num2'])
dff

   num1  num2
0     1     2
1     2     3
2     3     4

In [32]:
#creating a series from the dataframe
ss=dff[['num1','num2']]
print(ss)

   num1  num2
0     1     2
1     2     3
2     3     4

In [33]:
type(ss)

pandas.core.frame.DataFrame

# Dictionary to series and dataframe

In [3]:
#creat a dictionary
data ={
        'name':['Rashedul','jannat','Rishan'],
        'age':[25,24,23],
        'city':['Dhaka','Noakhali','khulna']
}
data

{'name': ['Rashedul', 'jannat', 'Rishan'],
 'age': [25, 24, 23],
 'city': ['Dhaka', 'Noakhali', 'khulna']}

In [4]:
#create a series from the dictionary
name_series=pd.Series(data['name'])
name_series

0    Rashedul
1      jannat
2      Rishan
dtype: object

In [4]:
#create a dataframe from dictionary
ddf=pd.DataFrame(data)
ddf

       name  age      city
0  Rashedul   25     Dhaka
1    jannat   24  Noakhali
2    Rishan   23    khulna

## set to series and dataframe

In [5]:
s1={1,2,3,4,5}

In [9]:
s=pd.Series(list(s1))
s

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [13]:
df=pd.DataFrame(s1,columns=['set value'])
df

   set value
0          1
1          2
2          3
3          4
4          5

## Tuple to Series and Dataframe

In [15]:
t=(1,2,3,4,5,True,False)
s=pd.Series(t)
s

0        1
1        2
2        3
3        4
4        5
5     True
6    False
dtype: object

In [17]:
df=pd.DataFrame(t,columns=['Value'])
df

   Value
0      1
1      2
2      3
3      4
4      5
5   True
6  False

In [18]:
type(df)

pandas.core.frame.DataFrame