## Reading data from CSV/Excel

In [2]:
import pandas as pd

In [3]:
df=pd.read_excel('Data.xlsx')

In [4]:
df

   ID  Marks
0   1     80
1   2     85
2   3     90
3   4     70
4   5     75

In [5]:
df=pd.read_excel('Data.xlsx',sheet_name='Sheet2')
df

   ID Name
0   1   Mm
1   2   Nn
2   3   Rr
3   4   Pp
4   5   Ss

In [9]:
dff=pd.read_csv('data1.csv')
dff

   ID   Age  Salary
0    1   32   80000
1    2   42   75000
2    3   30   70000
3    4   26   65000
4    5   45   65000

## Reading dataset from Github using requests

In [11]:
!pip install requests

Requirement already satisfied: requests in d:\anaconda\lib\site-packages (2.32.5)
Requirement already satisfied: charset_normalizer<4,>=2 in d:\anaconda\lib\site-packages (from requests) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in d:\anaconda\lib\site-packages (from requests) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in d:\anaconda\lib\site-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in d:\anaconda\lib\site-packages (from requests) (2026.1.4)

In [13]:
import pandas as pd
import requests
from io import StringIO

Here,the request.get() function is used to send an HTTP GET request to the specified URL. This function returns a Response object and you have assigned it to the variable response.This object contains the server's response to the request.

In [20]:
url ='https://github.com/HabibaMaisa/Pandas_learning/raw/main/mental_health.csv'
response=requests.get(url)

The StringIO class from the module is used to create a file-like object from the text content of the response.response.text contains the content of the CSV file as a string and StringIO helps to treat this string as a file-like object that pd.read_csv can read.

In [21]:
csv_content = StringIO(response.text)

In [22]:
ddf=pd.read_csv(csv_content)
ddf.head()

,Person_ID,Age,Gender,Occupation,Daily_Screen_Time,Social_Media_Usage,Night_Usage,Sleep_Hours,Stress_Level,Work_Study_Hours,Physical_Activity,Social_Interaction_Score,Caffeine_Intake,Smoking,Alcohol,Depression,Anxiety,Burnout
0,1,54,Male,Student,10.2,7.5,0,6.5,8,5.8,Low,6,2,0,1,1,1,1
1,2,44,Male,Student,6.8,4.5,0,5.1,4,7.9,High,2,1,1,0,0,0,0
2,3,30,Male,Employed,5.5,6.9,0,3.5,10,9.4,Low,2,0,1,1,1,0,1
3,4,58,Male,Employed,5.6,4.1,0,9.0,2,2.0,High,10,0,0,1,0,0,0
4,5,23,Female,Employed,10.1,6.0,1,3.8,4,4.6,Low,4,4,0,1,1,1,0

In [23]:
ddf.shape

(2000, 18)

## Reading Dataset from github using direct raw data URL

In [24]:
url='https://raw.githubusercontent.com/HabibaMaisa/Pandas_learning/refs/heads/main/mental_health.csv'
data=pd.read_csv(url)
data.head()

,Person_ID,Age,Gender,Occupation,Daily_Screen_Time,Social_Media_Usage,Night_Usage,Sleep_Hours,Stress_Level,Work_Study_Hours,Physical_Activity,Social_Interaction_Score,Caffeine_Intake,Smoking,Alcohol,Depression,Anxiety,Burnout
0,1,54,Male,Student,10.2,7.5,0,6.5,8,5.8,Low,6,2,0,1,1,1,1
1,2,44,Male,Student,6.8,4.5,0,5.1,4,7.9,High,2,1,1,0,0,0,0
2,3,30,Male,Employed,5.5,6.9,0,3.5,10,9.4,Low,2,0,1,1,1,0,1
3,4,58,Male,Employed,5.6,4.1,0,9.0,2,2.0,High,10,0,0,1,0,0,0
4,5,23,Female,Employed,10.1,6.0,1,3.8,4,4.6,Low,4,4,0,1,1,1,0

## Reading dataset from Github using web get

In [26]:
!pip install wget

Requirement already satisfied: wget in d:\anaconda\lib\site-packages (3.2)

In [27]:
import wget 
#replace the URL with raw URL of my CSV file on Github
url = 'https://raw.githubusercontent.com/HabibaMaisa/Pandas_learning/refs/heads/main/mental_health.csv'
#Use wget to download the CSV file
file_path=wget.download(url)

100% [............................................................................] 125681 / 125681

In [28]:
data1=pd.read_csv(url)
data1

,Person_ID,Age,Gender,Occupation,Daily_Screen_Time,Social_Media_Usage,Night_Usage,Sleep_Hours,Stress_Level,Work_Study_Hours,Physical_Activity,Social_Interaction_Score,Caffeine_Intake,Smoking,Alcohol,Depression,Anxiety,Burnout
0,1,54,Male,Student,10.2,7.5,0,6.5,8,5.8,Low,6,2,0,1,1,1,1
1,2,44,Male,Student,6.8,4.5,0,5.1,4,7.9,High,2,1,1,0,0,0,0
2,3,30,Male,Employed,5.5,6.9,0,3.5,10,9.4,Low,2,0,1,1,1,0,1
3,4,58,Male,Employed,5.6,4.1,0,9.0,2,2.0,High,10,0,0,1,0,0,0
4,5,23,Female,Employed,10.1,6.0,1,3.8,4,4.6,Low,4,4,0,1,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,1996,49,Female,Employed,4.8,4.0,1,8.0,1,9.8,Medium,5,0,1,1,1,0,0
1996,1997,33,Male,Employed,2.7,2.6,0,7.2,9,10.1,Low,8,1,1,1,1,1,1
1997,1998,28,Male,Employed,2.6,4.6,0,6.5,10,7.7,Medium,6,2,0,0,0,1,1
1998,1999,56,Female,Student,3.2,2.8,1,8.3,9,2.1,High,5,0,1,1,0,0,0
1999,2000,38,Male,Unemployed,7.8,7.6,0,7.2,7,9.6,Low,1,3,0,1,1,0,1

In [29]:
data1.shape

(2000, 18)